language: node_js
node_js:
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
before_install:
    - npm install
    - npm install -g grunt
    - npm install -g jest
script: grunt test