image: Ubuntu
# Instalaciones de modulos y software necesarios
install:
    - docker pull sarasolera/proyectoseries
    
# Ejecuciones
test_script:
    - docker run -t -v `pwd`:/test sarasolera/proyectoseries

build: off

